/*
 * Pins.hpp
 *
 *  Created on: 5 mar 2015
 *      Author: marek
 */

#ifndef PINS_HPP_
#define PINS_HPP_

#define INPUTS_COUNT 0

#define OUTPUT_CHRISTMAS_LIGHTS_0_PORT 26
#define OUTPUT_CHRISTMAS_LIGHTS_1_PORT 27
#define OUTPUT_CHRISTMAS_LIGHTS_2_PORT 46
#define OUTPUT_CHRISTMAS_LIGHTS_SANTA_CLAUS_ROAD 47
#define OUTPUT_CHRISTMAS_LIGHTS_SANTA_CLAUS_STARS 45
#define OUTPUT_CHRISTMAS_LIGHTS_SANTA_CLAUS 44


#endif /* PINS_HPP_ */
